apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      template:
        spec:
          containers:
            - name: pytorch
              image: "{{ .Values.distributed.image.image_name }}:{{ .Values.distributed.image.image_tag }}"
              imagePullPolicy: Always
              command:
                - torchrun
                - --node-rank=$(RANK)
                - "examples/huggingface/pytorch/text-classification/distillation/run_glue.py"
                - --model_name_or_path
                - {{ .Values.distributed.model_name_or_path }}
                - --teacher_model_name_or_path
                - {{ .Values.distributed.teacher_model_name_or_path }}
                - --task_name
                - {{ .Values.distributed.task_name }}
                - --distillation
                - --do_train
                - --do_eval
                - --output_dir
                - /tmp/output
                - --per_device_train_batch_size
                - "{{ .Values.distributed.train.batch_size }}"
                - --per_device_eval_batch_size
                - "{{ .Values.distributed.eval.batch_size }}"
                - --no_cuda
              resources:
                limits:
                  cpu: {{ .Values.distributed.resources.cpu }}
                  memory: {{ .Values.distributed.resources.memory }}
              volumeMounts:
              - name: output-dir
                mountPath: /tmp/output
          volumes:
          - name: dshm
            emptyDir:
              medium: Memory
          - name: output-dir
            persistentVolumeClaim:
              claimName: {{ .Values.pvc.name }}
    Worker:
      replicas: {{ .Values.distributed.workers }}
      template:
        spec:
          containers:
            - name: pytorch
              image: "{{ .Values.distributed.image.image_name }}:{{ .Values.distributed.image.image_tag }}"
              imagePullPolicy: Always
              command:
                - torchrun
                - --node-rank=$(RANK)
                - "examples/huggingface/pytorch/text-classification/distillation/run_glue.py"
                - --model_name_or_path
                - {{ .Values.distributed.model_name_or_path }}
                - --teacher_model_name_or_path
                - {{ .Values.distributed.teacher_model_name_or_path }}
                - --task_name
                - {{ .Values.distributed.task_name }}
                - --distillation
                - --do_train
                - --do_eval
                - --output_dir
                - /tmp/output
                - --per_device_train_batch_size
                - "{{ .Values.distributed.train.batch_size }}"
                - --per_device_eval_batch_size
                - "{{ .Values.distributed.eval.batch_size }}"
                - --no_cuda
              resources:
                limits:
                  cpu: {{ .Values.distributed.resources.cpu }}
                  memory: {{ .Values.distributed.resources.memory }}
              volumeMounts:
              - name: output-dir
                mountPath: /tmp/output
          volumes:
          - name: dshm
            emptyDir:
              medium: Memory
          - name: output-dir
            persistentVolumeClaim:
              claimName: {{ .Values.pvc.name }}
